# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConsoleGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ConsoleGroupBox.setStyleSheet("    font-size: 12pt;\n"
"    font-family: Arial, sans-serif;")
        self.ConsoleGroupBox.setObjectName("ConsoleGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ConsoleGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.programFileLabel = QtWidgets.QLabel(self.ConsoleGroupBox)
        self.programFileLabel.setObjectName("programFileLabel")
        self.horizontalLayout.addWidget(self.programFileLabel)
        self.flashStatusLabel = QtWidgets.QLabel(self.ConsoleGroupBox)
        self.flashStatusLabel.setObjectName("flashStatusLabel")
        self.horizontalLayout.addWidget(self.flashStatusLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.programFileComboBox = QtWidgets.QComboBox(self.ConsoleGroupBox)
        self.programFileComboBox.setObjectName("programFileComboBox")
        self.verticalLayout_2.addWidget(self.programFileComboBox)
        self.flashButton = QtWidgets.QPushButton(self.ConsoleGroupBox)
        self.flashButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Adjust the radius to make the corners more or less rounded */\n"
"    background-color: #3498db; /* Button\'s normal background color */\n"
"    color: white; /* Button\'s text color */\n"
"    padding: 5px 5px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"/* Hover state */\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Change background color on hover */\n"
"}\n"
"\n"
"/* Active state (when button is clicked) */\n"
"QPushButton:pressed {\n"
"    background-color: #2070a0; /* Change background color when clicked */\n"
"}")
        self.flashButton.setObjectName("flashButton")
        self.verticalLayout_2.addWidget(self.flashButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.devicesLabel = QtWidgets.QLabel(self.ConsoleGroupBox)
        self.devicesLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.devicesLabel.setObjectName("devicesLabel")
        self.verticalLayout_5.addWidget(self.devicesLabel)
        self.devicesTableView = QtWidgets.QTableView(self.ConsoleGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesTableView.sizePolicy().hasHeightForWidth())
        self.devicesTableView.setSizePolicy(sizePolicy)
        self.devicesTableView.setObjectName("devicesTableView")
        self.verticalLayout_5.addWidget(self.devicesTableView)
        self.hotKeyLabel = QtWidgets.QLabel(self.ConsoleGroupBox)
        self.hotKeyLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.hotKeyLabel.setStyleSheet("")
        self.hotKeyLabel.setObjectName("hotKeyLabel")
        self.verticalLayout_5.addWidget(self.hotKeyLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addDeviceButton = QtWidgets.QPushButton(self.ConsoleGroupBox)
        self.addDeviceButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Adjust the radius to make the corners more or less rounded */\n"
"    background-color: #3498db; /* Button\'s normal background color */\n"
"    color: white; /* Button\'s text color */\n"
"    padding: 5px 0px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"/* Hover state */\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Change background color on hover */\n"
"}\n"
"\n"
"/* Active state (when button is clicked) */\n"
"QPushButton:pressed {\n"
"    background-color: #2070a0; /* Change background color when clicked */\n"
"}")
        self.addDeviceButton.setObjectName("addDeviceButton")
        self.horizontalLayout_5.addWidget(self.addDeviceButton)
        self.printNowButton = QtWidgets.QPushButton(self.ConsoleGroupBox)
        self.printNowButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Adjust the radius to make the corners more or less rounded */\n"
"    background-color: #3498db; /* Button\'s normal background color */\n"
"    color: white; /* Button\'s text color */\n"
"    padding: 5px 0px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"/* Hover state */\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Change background color on hover */\n"
"}\n"
"\n"
"/* Active state (when button is clicked) */\n"
"QPushButton:pressed {\n"
"    background-color: #2070a0; /* Change background color when clicked */\n"
"}")
        self.printNowButton.setObjectName("printNowButton")
        self.horizontalLayout_5.addWidget(self.printNowButton)
        self.clearListButton = QtWidgets.QPushButton(self.ConsoleGroupBox)
        self.clearListButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Adjust the radius to make the corners more or less rounded */\n"
"    background-color: #3498db; /* Button\'s normal background color */\n"
"    color: white; /* Button\'s text color */\n"
"    padding: 5px 0px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"/* Hover state */\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Change background color on hover */\n"
"}\n"
"\n"
"/* Active state (when button is clicked) */\n"
"QPushButton:pressed {\n"
"    background-color: #2070a0; /* Change background color when clicked */\n"
"}")
        self.clearListButton.setObjectName("clearListButton")
        self.horizontalLayout_5.addWidget(self.clearListButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.ConsoleGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConsoleGroupBox.setTitle(_translate("MainWindow", "Console"))
        self.programFileLabel.setText(_translate("MainWindow", "Select Your Hex/Bin File"))
        self.flashStatusLabel.setText(_translate("MainWindow", "Flash Status : None"))
        self.flashButton.setText(_translate("MainWindow", "Flash Program"))
        self.devicesLabel.setText(_translate("MainWindow", "Devices for Label Printing"))
        self.hotKeyLabel.setText(_translate("MainWindow", "Press Enter : Add Devices"))
        self.addDeviceButton.setText(_translate("MainWindow", "Add Devices"))
        self.printNowButton.setText(_translate("MainWindow", "Print Now"))
        self.clearListButton.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
